#!/bin/sh
# Run unit tests
deno task test-unit

# Run test coverage
deno task test-coverage
if [ $? -ne 0 ]; then
  echo "Test coverage generation failed. Aborting commit."
  exit 1
fi

# Stage the coverage report file for commit
git add tests/coverage-report.txt

# allow the commit
exit 0