#!/bin/sh
# Run unit tests
deno task unit-test

# Check the exit status of the test command
if [ $? -ne 0 ]; then
  echo "Unit tests failed. Aborting commit."
  exit 1
fi

# If tests pass, allow the commit
exit 0